# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Projects\Research\Medical\MedicalLabelMe\src/view\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 5, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.lineEditImageName = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditImageName.sizePolicy().hasHeightForWidth())
        self.lineEditImageName.setSizePolicy(sizePolicy)
        self.lineEditImageName.setReadOnly(True)
        self.lineEditImageName.setObjectName("lineEditImageName")
        self.verticalLayout_4.addWidget(self.lineEditImageName)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.lineEditAnnotationName = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditAnnotationName.sizePolicy().hasHeightForWidth())
        self.lineEditAnnotationName.setSizePolicy(sizePolicy)
        self.lineEditAnnotationName.setReadOnly(True)
        self.lineEditAnnotationName.setObjectName("lineEditAnnotationName")
        self.verticalLayout_4.addWidget(self.lineEditAnnotationName)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.lineEditImageSize = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditImageSize.sizePolicy().hasHeightForWidth())
        self.lineEditImageSize.setSizePolicy(sizePolicy)
        self.lineEditImageSize.setReadOnly(True)
        self.lineEditImageSize.setObjectName("lineEditImageSize")
        self.verticalLayout_4.addWidget(self.lineEditImageSize)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.valueUnderCursorList = QtWidgets.QListWidget(self.groupBox)
        self.valueUnderCursorList.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.valueUnderCursorList.setObjectName("valueUnderCursorList")
        self.verticalLayout_4.addWidget(self.valueUnderCursorList)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.xSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.xSpinBox.setPrefix("")
        self.xSpinBox.setMinimum(1)
        self.xSpinBox.setObjectName("xSpinBox")
        self.horizontalLayout_3.addWidget(self.xSpinBox)
        self.ySpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.ySpinBox.setMinimum(1)
        self.ySpinBox.setObjectName("ySpinBox")
        self.horizontalLayout_3.addWidget(self.ySpinBox)
        self.zSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.zSpinBox.setMinimum(1)
        self.zSpinBox.setObjectName("zSpinBox")
        self.horizontalLayout_3.addWidget(self.zSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 1, 1, 1)
        self.windowBottomSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.windowBottomSpinBox.setMinimum(-10000)
        self.windowBottomSpinBox.setMaximum(10000)
        self.windowBottomSpinBox.setSingleStep(10)
        self.windowBottomSpinBox.setObjectName("windowBottomSpinBox")
        self.gridLayout_3.addWidget(self.windowBottomSpinBox, 3, 0, 1, 1)
        self.windowLevelSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windowLevelSpinBox.sizePolicy().hasHeightForWidth())
        self.windowLevelSpinBox.setSizePolicy(sizePolicy)
        self.windowLevelSpinBox.setMinimum(-10000)
        self.windowLevelSpinBox.setMaximum(10000)
        self.windowLevelSpinBox.setSingleStep(10)
        self.windowLevelSpinBox.setProperty("value", 200)
        self.windowLevelSpinBox.setObjectName("windowLevelSpinBox")
        self.gridLayout_3.addWidget(self.windowLevelSpinBox, 1, 0, 1, 1)
        self.windowWidthSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.windowWidthSpinBox.setMinimum(1)
        self.windowWidthSpinBox.setMaximum(10000)
        self.windowWidthSpinBox.setSingleStep(10)
        self.windowWidthSpinBox.setProperty("value", 400)
        self.windowWidthSpinBox.setObjectName("windowWidthSpinBox")
        self.gridLayout_3.addWidget(self.windowWidthSpinBox, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.windowTopspinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.windowTopspinBox.setMinimum(-10000)
        self.windowTopspinBox.setMaximum(10000)
        self.windowTopspinBox.setSingleStep(10)
        self.windowTopspinBox.setProperty("value", 400)
        self.windowTopspinBox.setObjectName("windowTopspinBox")
        self.gridLayout_3.addWidget(self.windowTopspinBox, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.aGraphicsView = ASCGraphicsView(self.centralwidget)
        self.aGraphicsView.setMinimumSize(QtCore.QSize(300, 100))
        self.aGraphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.aGraphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.aGraphicsView.setDragMode(QtWidgets.QGraphicsView.NoDrag)
        self.aGraphicsView.setObjectName("aGraphicsView")
        self.horizontalLayout_7.addWidget(self.aGraphicsView)
        self.aSliceScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.aSliceScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.aSliceScrollBar.setObjectName("aSliceScrollBar")
        self.horizontalLayout_7.addWidget(self.aSliceScrollBar)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.sGraphicsView = ASCGraphicsView(self.centralwidget)
        self.sGraphicsView.setMinimumSize(QtCore.QSize(300, 100))
        self.sGraphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sGraphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sGraphicsView.setObjectName("sGraphicsView")
        self.horizontalLayout_8.addWidget(self.sGraphicsView)
        self.sSliceScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.sSliceScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.sSliceScrollBar.setObjectName("sSliceScrollBar")
        self.horizontalLayout_8.addWidget(self.sSliceScrollBar)
        self.gridLayout.addLayout(self.horizontalLayout_8, 0, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cGraphicsView = ASCGraphicsView(self.centralwidget)
        self.cGraphicsView.setMinimumSize(QtCore.QSize(300, 100))
        self.cGraphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cGraphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cGraphicsView.setObjectName("cGraphicsView")
        self.horizontalLayout_9.addWidget(self.cGraphicsView)
        self.cSliceScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.cSliceScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.cSliceScrollBar.setObjectName("cSliceScrollBar")
        self.horizontalLayout_9.addWidget(self.cSliceScrollBar)
        self.gridLayout.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setMinimumSize(QtCore.QSize(300, 100))
        self.openGLWidget.setObjectName("openGLWidget")
        self.gridLayout.addWidget(self.openGLWidget, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.refreshTargetListButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshTargetListButton.setObjectName("refreshTargetListButton")
        self.horizontalLayout_5.addWidget(self.refreshTargetListButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.targetList = QtWidgets.QListWidget(self.centralwidget)
        self.targetList.setObjectName("targetList")
        self.verticalLayout_2.addWidget(self.targetList)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelOpacitySpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.labelOpacitySpinBox.setMaximum(100)
        self.labelOpacitySpinBox.setSingleStep(1)
        self.labelOpacitySpinBox.setProperty("value", 50)
        self.labelOpacitySpinBox.setObjectName("labelOpacitySpinBox")
        self.horizontalLayout_6.addWidget(self.labelOpacitySpinBox)
        self.labelOpacitySlider = QtWidgets.QSlider(self.centralwidget)
        self.labelOpacitySlider.setMaximum(100)
        self.labelOpacitySlider.setProperty("value", 50)
        self.labelOpacitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.labelOpacitySlider.setObjectName("labelOpacitySlider")
        self.horizontalLayout_6.addWidget(self.labelOpacitySlider)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.deleteTargetButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteTargetButton.setObjectName("deleteTargetButton")
        self.verticalLayout_2.addWidget(self.deleteTargetButton)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.opModeTab = QtWidgets.QTabWidget(self.centralwidget)
        self.opModeTab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.opModeTab.setObjectName("opModeTab")
        self.cursor = QtWidgets.QWidget()
        self.cursor.setObjectName("cursor")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cursor)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.cursor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.opModeTab.addTab(self.cursor, "")
        self.brush = QtWidgets.QWidget()
        self.brush.setObjectName("brush")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.brush)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_15 = QtWidgets.QLabel(self.brush)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rectRadioButton = QtWidgets.QRadioButton(self.brush)
        self.rectRadioButton.setObjectName("rectRadioButton")
        self.horizontalLayout_4.addWidget(self.rectRadioButton)
        self.circleRadioButton = QtWidgets.QRadioButton(self.brush)
        self.circleRadioButton.setChecked(True)
        self.circleRadioButton.setObjectName("circleRadioButton")
        self.horizontalLayout_4.addWidget(self.circleRadioButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.label_14 = QtWidgets.QLabel(self.brush)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.brushSizeSpinBox = QtWidgets.QSpinBox(self.brush)
        self.brushSizeSpinBox.setMinimum(1)
        self.brushSizeSpinBox.setMaximum(40)
        self.brushSizeSpinBox.setProperty("value", 5)
        self.brushSizeSpinBox.setObjectName("brushSizeSpinBox")
        self.horizontalLayout_2.addWidget(self.brushSizeSpinBox)
        self.brushSizeSlider = QtWidgets.QSlider(self.brush)
        self.brushSizeSlider.setMinimum(1)
        self.brushSizeSlider.setMaximum(40)
        self.brushSizeSlider.setProperty("value", 5)
        self.brushSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brushSizeSlider.setObjectName("brushSizeSlider")
        self.horizontalLayout_2.addWidget(self.brushSizeSlider)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.opModeTab.addTab(self.brush, "")
        self.verticalLayout_2.addWidget(self.opModeTab)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        self.horizontalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1011, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionToggle_Label_Visibility = QtWidgets.QAction(MainWindow)
        self.actionToggle_Label_Visibility.setObjectName("actionToggle_Label_Visibility")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionToggle_Label_Visibility)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.opModeTab.setCurrentIndex(0)
        self.actionExit.triggered.connect(MainWindow.close)
        self.actionOpen.triggered.connect(MainWindow.menu_open_triggered)
        self.aGraphicsView.scale_signal['float', 'float'].connect(MainWindow.scale_all_scenes)
        self.aGraphicsView.move_focus_point_signal['int', 'int', 'int'].connect(MainWindow.move_focus_point)
        self.aGraphicsView.set_focus_point_signal['int', 'int', 'int'].connect(MainWindow.set_focus_point)
        MainWindow.set_cross_bar_signal['int','int','int'].connect(self.aGraphicsView.set_cross_bar)
        MainWindow.set_cross_bar_signal['int','int','int'].connect(self.sGraphicsView.set_cross_bar)
        self.sGraphicsView.move_focus_point_signal['int','int','int'].connect(MainWindow.move_focus_point)
        self.sGraphicsView.scale_signal['float','float'].connect(MainWindow.scale_all_scenes)
        self.sGraphicsView.set_focus_point_signal['int','int','int'].connect(MainWindow.set_focus_point)
        MainWindow.set_cross_bar_signal['int','int','int'].connect(self.cGraphicsView.set_cross_bar)
        self.cGraphicsView.move_focus_point_signal['int','int','int'].connect(MainWindow.move_focus_point)
        self.cGraphicsView.scale_signal['float','float'].connect(MainWindow.scale_all_scenes)
        self.cGraphicsView.set_focus_point_signal['int','int','int'].connect(MainWindow.set_focus_point)
        self.xSpinBox.valueChanged['int'].connect(MainWindow.on_x_spin_box_value_changed)
        self.ySpinBox.valueChanged['int'].connect(MainWindow.on_y_spin_box_value_changed)
        self.zSpinBox.valueChanged['int'].connect(MainWindow.on_z_spin_box_value_changed)
        self.windowLevelSpinBox.valueChanged['int'].connect(MainWindow.on_window_level_spin_box_value_changed)
        self.windowWidthSpinBox.valueChanged['int'].connect(MainWindow.on_window_width_spin_box_value_changed)
        self.targetList.itemClicked['QListWidgetItem*'].connect(MainWindow.on_target_list_item_clicked)
        self.brushSizeSpinBox.valueChanged['int'].connect(self.brushSizeSlider.setValue)
        self.brushSizeSlider.valueChanged['int'].connect(self.brushSizeSpinBox.setValue)
        self.opModeTab.currentChanged['int'].connect(MainWindow.on_current_op_mode_tab_changed)
        self.brushSizeSlider.valueChanged['int'].connect(MainWindow.on_brush_size_changed)
        MainWindow.set_brush_stats_signal['int', 'int'].connect(self.aGraphicsView.set_brush_stats)
        MainWindow.set_brush_stats_signal['int', 'int'].connect(self.sGraphicsView.set_brush_stats)
        MainWindow.set_brush_stats_signal['int', 'int'].connect(self.cGraphicsView.set_brush_stats)
        self.circleRadioButton.clicked.connect(MainWindow.on_brush_type_clicked)
        self.rectRadioButton.clicked.connect(MainWindow.on_brush_type_clicked)
        self.aGraphicsView.paint_anno_on_point_signal['int', 'int', 'int', 'int', 'int', 'bool', 'bool'].connect(
            MainWindow.on_paint_on_point)
        self.sGraphicsView.paint_anno_on_point_signal['int', 'int', 'int', 'int', 'int', 'bool', 'bool'].connect(
            MainWindow.on_paint_on_point)
        self.cGraphicsView.paint_anno_on_point_signal['int', 'int', 'int', 'int', 'int', 'bool', 'bool'].connect(
            MainWindow.on_paint_on_point)
        self.refreshTargetListButton.clicked.connect(MainWindow.on_refresh_list_button_clicked)
        self.deleteTargetButton.clicked.connect(MainWindow.on_delete_target_button_clicked)
        self.actionClose.triggered.connect(MainWindow.menu_close_triggered)
        self.actionSave.triggered.connect(MainWindow.menu_save_triggered)
        self.aSliceScrollBar.valueChanged['int'].connect(self.aGraphicsView.on_slice_scroll_bar_changed)
        self.sSliceScrollBar.valueChanged['int'].connect(self.sGraphicsView.on_slice_scroll_bar_changed)
        self.cSliceScrollBar.valueChanged['int'].connect(self.cGraphicsView.on_slice_scroll_bar_changed)
        self.aGraphicsView.set_focus_point_percent_signal['float', 'float', 'float'].connect(
            MainWindow.set_focus_point_by_ratio)
        self.sGraphicsView.set_focus_point_percent_signal['float', 'float', 'float'].connect(
            MainWindow.set_focus_point_by_ratio)
        self.windowBottomSpinBox.valueChanged['int'].connect(MainWindow.on_window_bottom_spin_box_value_changed)
        self.windowTopspinBox.valueChanged['int'].connect(MainWindow.on_window_top_spin_box_value_changed)
        self.cGraphicsView.set_focus_point_percent_signal['float', 'float', 'float'].connect(
            MainWindow.set_focus_point_by_ratio)
        self.labelOpacitySpinBox.valueChanged['int'].connect(self.labelOpacitySlider.setValue)
        self.labelOpacitySlider.valueChanged['int'].connect(self.labelOpacitySpinBox.setValue)
        self.labelOpacitySpinBox.valueChanged['int'].connect(MainWindow.on_label_opacity_spin_box_changed)
        self.actionUndo.triggered.connect(MainWindow.menu_undo_paint_triggered)
        self.actionRedo.triggered.connect(MainWindow.menu_redo_paint_triggered)
        self.actionToggle_Label_Visibility.triggered.connect(MainWindow.menu_toggle_label_visibility)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Medical Labelme"))
        self.label_6.setText(_translate("MainWindow", "Information:"))
        self.label_3.setText(_translate("MainWindow", "Image:"))
        self.lineEditImageName.setText(_translate("MainWindow", "Null"))
        self.label_5.setText(_translate("MainWindow", "Annotation:"))
        self.lineEditAnnotationName.setText(_translate("MainWindow", "Null"))
        self.label_7.setText(_translate("MainWindow", "Image Size (x,y,z):"))
        self.lineEditImageSize.setText(_translate("MainWindow", "(0, 0, 0)"))
        self.label_4.setText(_translate("MainWindow", "Value Under Cursor:"))
        self.label_2.setText(_translate("MainWindow", "Control:"))
        self.label.setText(_translate("MainWindow", "Cursor Position (x,y,z):"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Window:"))
        self.label_9.setText(_translate("MainWindow", "Width:"))
        self.label_8.setText(_translate("MainWindow", "Level:"))
        self.label_11.setText(_translate("MainWindow", "Top"))
        self.label_10.setText(_translate("MainWindow", "Bottom:"))
        self.label_12.setText(_translate("MainWindow", "Target list:"))
        self.refreshTargetListButton.setText(_translate("MainWindow", "Refresh"))
        self.label_17.setText(_translate("MainWindow", "Label Opacity (%):"))
        self.deleteTargetButton.setText(_translate("MainWindow", "Delete Selected Target"))
        self.label_13.setText(_translate("MainWindow", "Annotator"))
        self.label_16.setText(_translate("MainWindow", "Voxel selection mode."))
        self.opModeTab.setTabText(self.opModeTab.indexOf(self.cursor), _translate("MainWindow", "Cursor"))
        self.label_15.setText(_translate("MainWindow", "Paint brush mode."))
        self.rectRadioButton.setText(_translate("MainWindow", "Rect"))
        self.circleRadioButton.setText(_translate("MainWindow", "Circle"))
        self.label_14.setText(_translate("MainWindow", "Size:"))
        self.opModeTab.setTabText(self.opModeTab.indexOf(self.brush), _translate("MainWindow", "Brush"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionUndo.setText(_translate("MainWindow", "Undo Paint"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo Paint"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.actionToggle_Label_Visibility.setText(_translate("MainWindow", "Toggle Label Visibility"))
        self.actionToggle_Label_Visibility.setShortcut(_translate("MainWindow", "S"))


from controller.graphics_view_controller import ASCGraphicsView
